version: '3.8'

services:
  lavalink:
    image: fredboat/lavalink:4-alpine
    container_name: lavalink
    restart: always
    cpus: 4
    mem_limit: 1048M
    mem_reservation: 512M
    env_file:
      - ./env/lavalink/.env
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml # Mount application.yml or use environment variables
      - ./plugins:/opt/Lavalink/plugins # Persist plugins between restarts, ensure correct permissions (user: 322, group: 322)
    networks:
      - lava_network
    ports:
      - '127.0.0.1:2333:2333' 

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    cpus: 2
    mem_limit: 2048M
    mem_reservation: 512M
    ports:
      - '127.0.0.1:27017:27017'  
    volumes:
      - ./data/mongo_db:/data/db
      - ./ssl:/data/ssl:ro  
      - ./config/mongodb.conf:/etc/mongo/mongodb.conf:ro  
    env_file:
      - ./env/mongo/.env
    networks:
      - mongo_network

  redis:
    image: redis:latest
    container_name: redis
    cpus: 2
    mem_limit: 2048M
    mem_reservation: 512M
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./data/redis_data:/data/redis
    env_file:
      - ./env/redis/.env
    restart: always
    networks:
      - redis_network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    cpus: 2
    mem_limit: 2048M
    mem_reservation: 512M
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/db
    env_file:
      - ./env/postgres/.env
    networks:
      - postgres_network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  lava_network:
    driver: bridge
  mongo_network:
    driver: bridge
  redis_network:
    driver: bridge
  postgres_network:
    driver: bridge
