services:
  lavalink:
    image: fredboat/lavalink:4-alpine # pin the image version to Lavalink v4
    container_name: lava
    restart: always
    env_file:
      - ./env/lavalink/.env
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
      - ./plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    networks:
      - lava_net
    expose:
      - 2333
    ports:
      - '127.0.0.1:2333:2333'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - ./data/mongo_db:/data/db
      - ./ssl:/data/ssl
      - ./config/mongodb.conf:/data/mongodb.conf
    env_file:
      - ./env/mongo/.env
    networks:
      - mongo_net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      - redis_net
    volumes:
      - ./data/redis_data:/data/redis
    env_file:
      - ./env/redis/.env
    restart: always

volumes:
  mongo_db:
    name: mongo_db
    driver: local
  redis_data:
    name: redis_data
    driver: local

networks:
  lava_net:
    name: lava_net
  mongo_net:
    name: mongo_net
  redis_net:
    name: redis_net

