version: "3.8"

services:
  lavalink:
    image: fredboat/lavalink:latest
    container_name: lava
    configs:
      - source: lava
        target: ./opt/Lavalink/application.yml
    networks:
      - lava_net
    ports:
      - "2333:2333"
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo_db:/data/db
      - ./ssl:/ssl    # Mount SSL certificates directory
    env_file:
      - ./env/mongo/.env
    networks:
      - mongo_net
    command: ["mongod", "--tlsMode=requireTLS", "--tlsCertificateKeyFile=/ssl/mongodb.pem", "--tlsCAFile=/ssl/ca.pem"]
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis_net
    volumes:
      - ./data/redis_data:/data/redis
    env_file:
      - ./env/redis/.env
    restart: always

volumes:
  mongo_db:
    name: mongo_db
    driver: local
  redis_data:
    name: redis_data
    driver: local

networks:
  lava_net:
    name: lava_net
    external: true
  mongo_net:
    name: mongo_net
    external: true
  redis_net:
    name: redis_net
    external: true

configs:
  lava:
    name: lava
    file: ./application.yml
